# Generated by Django 2.0 on 2019-09-22 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True, verbose_name='用户id')),
                ('count', models.IntegerField(verbose_name='投入量')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='投入日期')),
            ],
            options={
                'verbose_name': '用户投入历史记录表',
                'verbose_name_plural': '用户投入历史记录表',
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=100, unique=True, verbose_name='用户id')),
                ('nickname', models.CharField(default='未知昵称', max_length=30, verbose_name='用户昵称')),
                ('location', models.CharField(default='宿舍信息尚未填写', max_length=30, verbose_name='宿舍楼栋与宿舍号')),
                ('all_touru', models.IntegerField(default=0, verbose_name='所有投入')),
                ('level', models.CharField(default='热心环保', max_length=20, verbose_name='环保等级')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_touru', to='index.History')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'managed': True,
            },
        ),
    ]
