# Generated by Django 2.0 on 2019-10-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=100, unique=True, verbose_name='用户id')),
                ('token', models.CharField(max_length=100, verbose_name='登录token')),
            ],
        ),
    ]
