# Generated by Django 2.0 on 2019-10-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, '普通用户'), (2, '志愿者'), (3, '管理员')], default=1),
        ),
    ]
