# Generated by Django 2.0 on 2019-10-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_myuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yuyue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30, verbose_name='预约地址')),
                ('yuyuetime', models.DateTimeField(auto_now=True, verbose_name='预约时间')),
            ],
        ),
    ]
