# Generated by Django 2.0 on 2019-10-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_yuyue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='history',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='open_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='用户open_id'),
        ),
    ]
