# Generated by Django 2.0 on 2019-10-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20191005_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='user_id',
            field=models.CharField(max_length=100, verbose_name='用户id'),
        ),
    ]
